;; NOTE: Assertions have been generated by update_lit_checks.py --all-items and should not be edited.

;; RUN: wasm-split %s -all --keep-funcs=use-funcs -g -o1 %t.1.wasm -o2 %t.2.wasm
;; RUN: wasm-dis %t.1.wasm | filecheck %s --check-prefix PRIMARY
;; RUN: wasm-dis %t.2.wasm | filecheck %s --check-prefix SECONDARY

(module

 (type $data-array (array i8))

 (type $elem-array (array externref))

 ;; SECONDARY:      (type $0 (func))

 ;; SECONDARY:      (type $1 (array i8))

 ;; SECONDARY:      (type $2 (array externref))

 ;; SECONDARY:      (memory $mem 0)
 (memory $mem 0)

 ;; SECONDARY:      (data $data "hello world")
 (data $data "hello world")

 ;; SECONDARY:      (table $0 5 funcref)

 ;; SECONDARY:      (elem $0 (i32.const 0) $data.drop $memory.init $array.new_data $array.new_elem $no-segment)

 ;; SECONDARY:      (elem $elem externref)
 (elem $elem externref)

 ;; SECONDARY:      (func $array.new_data
 ;; SECONDARY-NEXT:  (drop
 ;; SECONDARY-NEXT:   (array.new_data $1 $data
 ;; SECONDARY-NEXT:    (i32.const 0)
 ;; SECONDARY-NEXT:    (i32.const 0)
 ;; SECONDARY-NEXT:   )
 ;; SECONDARY-NEXT:  )
 ;; SECONDARY-NEXT: )

 ;; SECONDARY:      (func $array.new_elem
 ;; SECONDARY-NEXT:  (drop
 ;; SECONDARY-NEXT:   (array.new_elem $2 $elem
 ;; SECONDARY-NEXT:    (i32.const 0)
 ;; SECONDARY-NEXT:    (i32.const 0)
 ;; SECONDARY-NEXT:   )
 ;; SECONDARY-NEXT:  )
 ;; SECONDARY-NEXT: )

 ;; SECONDARY:      (func $data.drop
 ;; SECONDARY-NEXT:  (data.drop $data)
 ;; SECONDARY-NEXT: )
 (func $data.drop
  (data.drop $data)
 )

 ;; SECONDARY:      (func $memory.init
 ;; SECONDARY-NEXT:  (memory.init $data
 ;; SECONDARY-NEXT:   (i32.const 0)
 ;; SECONDARY-NEXT:   (i32.const 0)
 ;; SECONDARY-NEXT:   (i32.const 0)
 ;; SECONDARY-NEXT:  )
 ;; SECONDARY-NEXT: )
 (func $memory.init
  (memory.init $mem $data
   (i32.const 0)
   (i32.const 0)
   (i32.const 0)
  )
 )

 (func $array.new_data
  (drop
   (array.new_data $data-array $data
    (i32.const 0)
    (i32.const 0)
   )
  )
 )

 (func $array.new_elem
  (drop
   (array.new_elem $elem-array $elem
    (i32.const 0)
    (i32.const 0)
   )
  )
 )

 ;; SECONDARY:      (func $no-segment
 ;; SECONDARY-NEXT:  (nop)
 ;; SECONDARY-NEXT: )
 (func $no-segment
  (nop)
 )

 ;; PRIMARY:      (type $0 (func))

 ;; PRIMARY:      (import "placeholder.deferred" "0" (func $placeholder_0))

 ;; PRIMARY:      (import "placeholder.deferred" "1" (func $placeholder_1))

 ;; PRIMARY:      (import "placeholder.deferred" "2" (func $placeholder_2))

 ;; PRIMARY:      (import "placeholder.deferred" "3" (func $placeholder_3))

 ;; PRIMARY:      (import "placeholder.deferred" "4" (func $placeholder_4))

 ;; PRIMARY:      (table $0 5 funcref)

 ;; PRIMARY:      (elem $0 (i32.const 0) $placeholder_0 $placeholder_1 $placeholder_2 $placeholder_3 $placeholder_4)

 ;; PRIMARY:      (func $use-funcs
 ;; PRIMARY-NEXT:  (call_indirect (type $0)
 ;; PRIMARY-NEXT:   (i32.const 0)
 ;; PRIMARY-NEXT:  )
 ;; PRIMARY-NEXT:  (call_indirect (type $0)
 ;; PRIMARY-NEXT:   (i32.const 1)
 ;; PRIMARY-NEXT:  )
 ;; PRIMARY-NEXT:  (call_indirect (type $0)
 ;; PRIMARY-NEXT:   (i32.const 2)
 ;; PRIMARY-NEXT:  )
 ;; PRIMARY-NEXT:  (call_indirect (type $0)
 ;; PRIMARY-NEXT:   (i32.const 3)
 ;; PRIMARY-NEXT:  )
 ;; PRIMARY-NEXT:  (call_indirect (type $0)
 ;; PRIMARY-NEXT:   (i32.const 4)
 ;; PRIMARY-NEXT:  )
 ;; PRIMARY-NEXT: )
 (func $use-funcs
  (call $data.drop)
  (call $memory.init)
  (call $array.new_data)
  (call $array.new_elem)
  (call $no-segment)
 )
)
